apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: mysql-degraded-failover-scenario
  namespace: chaos-mesh
spec:
  entry: start-degradation-and-kill
  templates:
    - name: start-degradation-and-kill
      templateType: Parallel
      children:
        - inject-io-latency
        - delayed-kill-sequence

    - name: inject-io-latency
      templateType: IOChaos
      deadline: "2m"
      ioChaos:
        action: latency
        mode: one
        selector:
          namespaces: ["demo"]
          labelSelectors: {"app.kubernetes.io/instance": "mysql-ha-cluster", "kubedb.com/role": "primary"}
        volumePath: "/var/lib/mysql"
        delay: "50ms"
        percent: 100

    - name: delayed-kill-sequence
      templateType: Serial
      children:
        - wait-30s
        - kill-primary-pod

    - name: wait-30s
      templateType: Suspend
      deadline: "30s"

    - name: kill-primary-pod
      templateType: PodChaos
      deadline: "1m"
      podChaos:
        action: pod-kill
        mode: one
        selector:
          namespaces: ["demo"]
          labelSelectors: {"app.kubernetes.io/instance": "mysql-ha-cluster", "kubedb.com/role": "primary"}
