apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: mariadb-galera-network-latency
  namespace: chaos-mesh
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      app.kubernetes.io/instance: md
      kubedb.com/role: Primary
  target:
    mode: all
    selector:
      namespaces:
        - demo
      labelSelectors:
        app.kubernetes.io/instance: md
        kubedb.com/role: Primary
  delay:
    latency: "1s"
    jitter: "50ms"
  direction: both
  duration: 10m