apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: test-kubedb-primary-network-bandwidth
  namespace: demo
spec:
  selector:
    namespaces:
      - demo
    labelSelectors:
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: kubedb.com
      app.kubernetes.io/name: mysqls.kubedb.com
      kubedb.com/role: primary
  action: bandwidth
  mode: all
  bandwidth:
    rate: '1bps'
    limit: 20971520
    buffer: 10000
  duration: 2m
