apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: test-kubedb-primary-network-delay
  namespace: demo
spec:
  selector:
    namespaces:
      - demo
    labelSelectors:
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: kubedb.com
      app.kubernetes.io/name: mysqls.kubedb.com
      kubedb.com/role: primary
  mode: all
  action: delay
  delay:
    latency: 2000ms
    correlation: '100'
    jitter: 0ms
  direction: to
  duration: 2m
