apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: test-kubedb-primary-io-latency
  namespace: demo
spec:
  action: latency
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: kubedb.com
      app.kubernetes.io/name: mysqls.kubedb.com
      kubedb.com/role: primary
  volumePath: /var/lib/mysql
  path: '/var/lib/mysql/**/*'
  delay: '2000ms'
  percent: 100
  duration: 2m
