apiVersion: v1
kind: Secret
metadata:
  name: config
  namespace: demo
stringData:
  my.cnf: |-
    [mysqld]
    loose_group_replication_unreachable_majority_timeout = 20
#    loose_group_replication_member_expel_timeout = 120
---






