apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mysql-cpu-stress-5.7
  namespace: chaos-mesh
spec:
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "mysql-ha-cluster"
  stressors:
    cpu:
      workers: 2
      load: 98
  duration: "3m"
