apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: mariadb-primary-network-partition
  namespace: chaos-mesh
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "md"
      "kubedb.com/role": "Primary"
  target:
    mode: all
    selector:
      namespaces:
        - demo
      labelSelectors:
#        "app.kubernetes.io/instance": "md"
        "kubedb.com/role": "Primary"
#        "statefulset.kubernetes.io/pod-name": "md-0"
  direction: both
  duration: "2m"
