apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mariadb-replica-memory-stress
  namespace: chaos-mesh
spec:
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "md"
#      "kubedb.com/role": "Primary"
      "kubedb.com/role": "Primary"
  stressors:
    memory:
      workers: 1
      size: "800MB"
  duration: "20m"
