apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: md-slave-io-fault
  namespace: chaos-mesh
spec:
  action: fault
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "md"
      "kubedb.com/role": "Slave"
  volumePath: /var/lib/mysql
  path: "/**"
  errno: 5
  percent: 50
  duration: "2m"
  containerNames:
    - mariadb
