apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: md-slave-isolated
  namespace: chaos-mesh
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "md"
      "kubedb.com/role": "Slave"
  target:
    mode: all
    selector:
      namespaces:
        - demo
      labelSelectors:
        "app.kubernetes.io/instance": "md"
  direction: both
  duration: "90s"
