apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: mx-md-partition
  namespace: chaos-mesh
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "md-mx"
  target:
    mode: all
    selector:
      namespaces:
        - demo
      labelSelectors:
        "app.kubernetes.io/instance": "md"
  direction: both
  duration: "60s"
