apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: md-net-latency-1s
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "md"
  delay:
    latency: "1s"
    jitter: "50ms"
  duration: "60s"
  direction: both
