apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: md-packet-corrupt
  namespace: chaos-mesh
spec:
  action: corrupt
  mode: one
  selector:
    namespaces: [demo]
    labelSelectors:
      "app.kubernetes.io/instance": "md"
      "kubedb.com/role": "Master"
  target:
    mode: all
    selector:
      namespaces: [demo]
      labelSelectors:
        "app.kubernetes.io/instance": "md"
  corrupt:
    corrupt: "50"
    correlation: "25"
  duration: "45s"
  direction: both
