apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: md-maxscale-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - demo
    labelSelectors:
      "app.kubernetes.io/instance": "md-mx"
  gracePeriod: 0
