apiVersion: apps/v1
kind: Deployment
metadata:
  name: sysbench-load
  namespace: demo
  labels:
    app: sysbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysbench
  template:
    metadata:
      labels:
        app: sysbench
    spec:
      containers:
        - name: sysbench
          image: perconalab/sysbench:latest
          command: ["/bin/sleep", "infinity"]
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
            - name: MYSQL_HOST
              value: "md.demo.svc.cluster.local"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: md-auth
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: md-auth
                  key: password
            - name: MYSQL_DB
              value: "sbtest"
---
#clean
#sysbench oltp_write_only --mysql-host=md --mysql-port=3306 --mysql-user=root --mysql-password="${MYSQL_PASSWORD}" --mysql-db=sbtest --tables=12 cleanup

#prepare
#sysbench oltp_write_only --mysql-host=${MYSQL_HOST:-md.demo.svc.cluster.local} --mysql-port=${MYSQL_PORT:-3306} --mysql-user=${MYSQL_USER:-root} --mysql-password=${MYSQL_PASSWORD} --mysql-db=sbtest --tables=4 --table-size=50000 --threads=8 prepare

#run during chaos tests:
#sysbench oltp_write_only --mysql-host=md --mysql-port=3306 --mysql-user=root --mysql-password="${MYSQL_PASSWORD}" --mysql-db=sbtest --tables=4 --table-size=50000 --threads=16 --time=180 --report-interval=10 run
